import { Bank } from '@/types/bank';

export const banks: Bank[] = [
  {
    id: 80,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/7e434307-1ec1-42ae-9a72-d5dd5da43cb8.svg",
    smallLogoPath: "/images/bank/45dda78d-a9a7-4c69-8e3f-a3ba2a2c2b25.svg",
    name: "TestBanka",
    code: "TESTBANKA",
    financeType: 1,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 35,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/e4f54355-cef1-4b0b-ae3a-975809bbd4d0.png",
    smallLogoPath: null,
    name: "Citibank",
    code: "CB",
    financeType: 2,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 83,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ab74d739-3d02-49ae-9647-fa490e4abec5.svg",
    smallLogoPath: "/images/bank/fb87307c-c801-4ee1-94d5-9c4cbf95d9c9.svg",
    name: "İş Bankası- Burçin",
    code: "İş Bankası",
    financeType: 1,
    notes: "<p>test</p>\r\n",
    displayOrder: 0,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 81,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/833d2215-e748-4d99-92ef-8c40180d0191.svg",
    smallLogoPath: "",
    name: "PAYTR",
    code: "PYTR",
    financeType: 1,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 72,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/0855c9f3-d017-4ace-9eba-920763e34e0c.svg",
    smallLogoPath: "",
    name: "Tosla",
    code: "TS",
    financeType: 0,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 73,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/a4eab010-ac34-49c6-b45f-78206be9df51.svg",
    smallLogoPath: "",
    name: "Fiba Faktoring",
    code: "FIBAF",
    financeType: 2,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 82,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ab2f96cb-7651-4e71-ae1a-d27dd6d88972.svg",
    smallLogoPath: "/images/bank/cad225b2-5a3a-45b9-84ab-518e2fe29ea2.svg",
    name: "Deniz Faktoring ",
    code: "DF",
    financeType: 0,
    notes: "<p>test</p>\r\n",
    displayOrder: 0,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 76,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/8851fd39-a0ba-433b-a866-32c1c7f0a820.svg",
    smallLogoPath: "",
    name: "Türkiye İş Bankası - Digital Onboarding 2. satır durumu",
    code: "8765",
    financeType: 0,
    notes: null,
    displayOrder: 0,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 75,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/31417ebe-c3bc-44a5-b095-f423fe2c82c9.svg",
    smallLogoPath: "/images/bank/7d9bd4b1-9db1-4dc6-bf2a-af118b265e78.svg",
    name: "TESTTTTT",
    code: "AKB",
    financeType: 0,
    notes: "<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit.</p>\r\n",
    displayOrder: 0,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 30,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/cce22106-9db3-4240-a20f-7120df126525.svg",
    smallLogoPath: "/images/bank/c8c7e36c-6657-4062-aecd-616d40ebe99d.svg",
    name: "Akbank",
    code: "AB",
    financeType: 1,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 14,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/de019832-3131-4f0a-8753-fe613c85c01e.svg",
    smallLogoPath: "/images/bank/7887c720-867a-40f8-82b3-25f92839630b.png",
    name: "CEPTETEB",
    code: "CTEB",
    financeType: 1,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 8,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/cc94c4fe-edec-4625-b711-a8a6706de713.svg",
    smallLogoPath: "/images/bank/4db49256-cc11-4f9a-9ab3-487c72250d77.svg",
    name: "Albaraka Türk",
    code: "AT",
    financeType: 2,
    notes: "<title></title>\r\n",
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 1,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/fortisbank.svg",
    smallLogoPath: null,
    name: "FortisBank",
    code: "FOB",
    financeType: 2,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 29,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ing-logo-svg.svg",
    smallLogoPath: "/images/bank/ing-1.svg",
    name: "ING",
    code: "ING",
    financeType: 2,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 27,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/yapikredi.svg",
    smallLogoPath: "/images/bank/yapikredi.svg",
    name: "YapıKredi ",
    code: "YKB",
    financeType: 1,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 77,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/9794358b-d6e5-4718-a11e-061359800a03.svg",
    smallLogoPath: "",
    name: "Lidio",
    code: "lıd",
    financeType: 0,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 11,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/denizbank.svg",
    smallLogoPath: "/images/bank/denizbank-1.svg",
    name: "DenizBank",
    code: "DB",
    financeType: 4,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 20,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/kuveytturk.svg",
    smallLogoPath: "/images/bank/unnamed-1.svg",
    name: "Kuveyt Türk",
    code: "KT",
    financeType: 2,
    notes: null,
    displayOrder: 1,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 65,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/hk-kobi-3-2.svg",
    smallLogoPath: null,
    name: "Ön Ödemeli Kartlar",
    code: "150",
    financeType: 4,
    notes: "<p>asdasdqweq</p>\r\n",
    displayOrder: 2,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 25,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ed7af597-7847-44d8-8d82-cc66884f5c10.svg",
    smallLogoPath: null,
    name: "Şekerbank",
    code: "SB",
    financeType: 2,
    notes: null,
    displayOrder: 3,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 21,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/bankpozitif.svg",
    smallLogoPath: null,
    name: "BankPozitif",
    code: "BP",
    financeType: 1,
    notes: null,
    displayOrder: 4,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 71,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/1ff5c1a1-6af0-4af1-93ae-0ece10aeceb3.svg",
    smallLogoPath: "",
    name: "Paratikam",
    code: "PT",
    financeType: 0,
    notes: null,
    displayOrder: 5,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 32,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/hsbc.svg",
    smallLogoPath: "/images/bank/ef6c1048-58c8-4926-9788-51ff14ff1331.png",
    name: "HSBC",
    code: "HSBC",
    financeType: 4,
    notes: null,
    displayOrder: 5,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 70,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/924ab7d6-f60a-4a15-b034-d5f856ffa75f.svg",
    smallLogoPath: "/images/bank/e0dcf1f8-76c5-444b-bc69-8a527a499bcd.png",
    name: "TestBank",
    code: "TESTBANK",
    financeType: 1,
    notes: "<p>343</p>\r\n",
    displayOrder: 5,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 61,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ziraat-katilim-bankasi.svg",
    smallLogoPath: "/images/bank/1678803301basketball-ball.svg",
    name: "Ziraat Katılım",
    code: "Ziraat",
    financeType: 2,
    notes: null,
    displayOrder: 6,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 10,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/icbc.svg",
    smallLogoPath: "/images/bank/1398-1.svg",
    name: "ICBC Bank Turkey",
    code: "ICBC",
    financeType: 1,
    notes: null,
    displayOrder: 7,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 28,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/burganbank.svg",
    smallLogoPath: "/images/bank/burgan-1.svg",
    name: "Burgan Bank",
    code: "BU",
    financeType: 1,
    notes: null,
    displayOrder: 8,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 13,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/enpara.svg",
    smallLogoPath: "/images/bank/enpara.svg",
    name: "Enpara.com",
    code: "EP",
    financeType: 1,
    notes: null,
    displayOrder: 9,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 63,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/onbanklogo-02-(3).svg",
    smallLogoPath: null,
    name: "OnBank",
    code: "OnBank",
    financeType: 1,
    notes: "<p>sadassa</p>\r\n",
    displayOrder: 10,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 19,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/vakifkatilim.svg",
    smallLogoPath: null,
    name: "Vakıf Katılım",
    code: "VKK",
    financeType: 2,
    notes: null,
    displayOrder: 13,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 9,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/001ea967-e23a-4670-a6f1-15d501c80060.svg",
    smallLogoPath: "/images/bank/isbankasi.svg",
    name: "İş Bankası",
    code: "TIB",
    financeType: 1,
    notes: null,
    displayOrder: 14,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 17,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/kocfinans.svg",
    smallLogoPath: "/images/bank/1024x1024-1.svg",
    name: "Koçfinans",
    code: "KF",
    financeType: 1,
    notes: null,
    displayOrder: 16,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 62,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/bank.svg",
    smallLogoPath: null,
    name: "FastPay",
    code: "FastPay",
    financeType: 0,
    notes: null,
    displayOrder: 18,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 31,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/cd91c5ce-0fa3-4330-b231-c50e3e20587c.svg",
    smallLogoPath: "/images/bank/anadolubank-1.svg",
    name: "Anadolubank",
    code: "ADB",
    financeType: 1,
    notes: null,
    displayOrder: 19,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 69,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/nkolay.svg",
    smallLogoPath: null,
    name: "KaderBank",
    code: "KaderBank",
    financeType: 1,
    notes: "<p>test</p>\r\n",
    displayOrder: 20,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 12,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/turkiye-finans.svg",
    smallLogoPath: "/images/bank/tr-finans-1.svg",
    name: "Türkiye Finans",
    code: "TFB",
    financeType: 2,
    notes: null,
    displayOrder: 21,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 34,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/aktifbank.svg",
    smallLogoPath: "/images/bank/c0f7608e-020b-4d83-8d8a-5dad40634f6d.svg",
    name: "Aktif Bank",
    code: "A",
    financeType: 1,
    notes: null,
    displayOrder: 22,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 33,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ziraat.svg",
    smallLogoPath: null,
    name: "Ziraat Bankası",
    code: "ZB",
    financeType: 2,
    notes: "<title></title>\r\n",
    displayOrder: 23,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 18,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/1b2b5496-1c73-4b76-8bbf-d5bcae3f68f9.svg",
    smallLogoPath: "/images/bank/55ce2e74-0b7a-4ea5-a734-1b9a4585b1b3.svg",
    name: "N Kolay",
    code: "NK",
    financeType: 1,
    notes: null,
    displayOrder: 25,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 50,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/bank.svg",
    smallLogoPath: null,
    name: "FastPay",
    code: "FP",
    financeType: 1,
    notes: null,
    displayOrder: 26,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 7,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/garanti-1.svg",
    smallLogoPath: "/images/bank/garanti.svg",
    name: "Garanti Bankası",
    code: "GB",
    financeType: 2,
    notes: null,
    displayOrder: 27,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 22,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/seker-finans.svg",
    smallLogoPath: null,
    name: "Şeker Finans",
    code: "SF",
    financeType: 2,
    notes: null,
    displayOrder: 28,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 24,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/odeabank.svg",
    smallLogoPath: "/images/bank/odeabank-1.svg",
    name: "Odeabank",
    code: "ODB",
    financeType: 1,
    notes: null,
    displayOrder: 29,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 26,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/teb.svg",
    smallLogoPath: "/images/bank/teb-1.svg",
    name: "TEB - Türk Ekonomi Bankası",
    code: "TEB",
    financeType: 2,
    notes: null,
    displayOrder: 31,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 23,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/vakifbank.svg",
    smallLogoPath: null,
    name: "VakıfBank",
    code: "VB",
    financeType: 2,
    notes: null,
    displayOrder: 33,
    soeUrl: null,
    bankType: 2,
    categories: []
  },
  {
    id: 4,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/alternatifbankk.svg",
    smallLogoPath: "/images/bank/alternatifbank-1.svg",
    name: "Alternatif Bank",
    code: "ABB",
    financeType: 1,
    notes: "<title></title>\r\n<p></p>\r\n",
    displayOrder: 34,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 15,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/halkbank.svg",
    smallLogoPath: null,
    name: "Halkbank",
    code: "HB",
    financeType: 2,
    notes: null,
    displayOrder: 35,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 5,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/fibabank.svg",
    smallLogoPath: "/images/bank/fibabanka-1.svg",
    name: "Fibabanka",
    code: "FIB",
    financeType: 2,
    notes: null,
    displayOrder: 36,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 2,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/tebcetelem.svg",
    smallLogoPath: null,
    name: "TEB Cetelem",
    code: "TCET",
    financeType: 1,
    notes: null,
    displayOrder: 37,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 67,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/cepteteb.svg",
    smallLogoPath: "/images/bank/cepte-teb-1.svg",
    name: "Cepteteb YENİ",
    code: "Cepteteb",
    financeType: 1,
    notes: "<p>Test</p>\r\n",
    displayOrder: 38,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 68,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/fastpay-1.svg",
    smallLogoPath: null,
    name: "FastPay Yeni",
    code: "FastPay2",
    financeType: 1,
    notes: "<p>34</p>\r\n",
    displayOrder: 40,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 36,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/ssl.svg",
    smallLogoPath: null,
    name: "ALJ Finans",
    code: "ALJ",
    financeType: 1,
    notes: null,
    displayOrder: 41,
    soeUrl: null,
    bankType: null,
    categories: []
  },
  {
    id: 84,
    logoPath: "https://test-hkcdn.mncdn.com",
    smallLogoPath: "",
    name: "Hedef Portföy",
    code: "HDFP",
    financeType: 0,
    notes: "<p>test</p>\r\n",
    displayOrder: 99,
    soeUrl: null,
    bankType: 1,
    categories: []
  },
  {
    id: 16,
    logoPath: "https://test-hkcdn.mncdn.com/images/bank/qnb.svg",
    smallLogoPath: "/images/bank/qnb-finansbank.svg",
    name: "QNB Finansbank",
    code: "FB",
    financeType: 1,
    notes: null,
    displayOrder: 99,
    soeUrl: null,
    bankType: null,
    categories: []
  }
]; 