import { Data } from '@/types/data';

export const data: Data = {
  "widgets": [
    {
      "id": 378,
      "name": "Sıkça Sorulan Sorular Test",
      "shortDescription": "<p>Kısa Açıklama</p>\r\n",
      "type": 5,
      "link": "Link",
      "linkText": "LinkText",
      "details": [
        {
          "id": 2127,
          "title": "Test1",
          "subTitle": "Alt Başlık Test1",
          "description": "<ul>\r\n\t<li>a</li>\r\n\t<li>b</li>\r\n\t<li>c</li>\r\n\t<li>d</li>\r\n\t<li>e</li>\r\n</ul>\r\n",
          "buttonText": null,
          "backgroundColor": null,
          "link": null,
          "linkText": null,
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": null,
          "thirdLinkText": null,
          "linkTarget": null,
          "displayOrder": 1,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com",
          "createdOn": "2024-03-20T22:28:13.614356",
          "updatedOn": null
        },
        {
          "id": 2128,
          "title": "Test2",
          "subTitle": "Test2",
          "description": "<p>açıklama Test</p>\r\n",
          "buttonText": null,
          "backgroundColor": null,
          "link": null,
          "linkText": null,
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": null,
          "thirdLinkText": null,
          "linkTarget": null,
          "displayOrder": 2,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com",
          "createdOn": "2024-03-20T22:28:48.113873",
          "updatedOn": null
        },
        {
          "id": 2129,
          "title": "Test Ovul 3",
          "subTitle": "test",
          "description": "<p>test</p>\r\n",
          "buttonText": null,
          "backgroundColor": null,
          "link": null,
          "linkText": null,
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": null,
          "thirdLinkText": null,
          "linkTarget": null,
          "displayOrder": 3,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com",
          "createdOn": "2024-03-20T22:29:05.443471",
          "updatedOn": null
        },
        {
          "id": 2130,
          "title": "test4",
          "subTitle": "test",
          "description": "<p>test</p>\r\n",
          "buttonText": null,
          "backgroundColor": null,
          "link": null,
          "linkText": null,
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": null,
          "thirdLinkText": null,
          "linkTarget": null,
          "displayOrder": 4,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com",
          "createdOn": "2024-03-20T22:29:23.448961",
          "updatedOn": null
        },
        {
          "id": 2131,
          "title": "Test5",
          "subTitle": "Alt Başlık",
          "description": "<p><em><strong>desc</strong></em></p>\r\n\r\n<ol>\r\n\t<li><em><strong>desc</strong></em></li>\r\n\t<li><b><i>desc</i></b></li>\r\n\t<li><b><i>desc</i></b></li>\r\n\t<li><b><i>desc</i></b></li>\r\n</ol>\r\n",
          "buttonText": null,
          "backgroundColor": null,
          "link": null,
          "linkText": null,
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": null,
          "thirdLinkText": null,
          "linkTarget": null,
          "displayOrder": 5,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com",
          "createdOn": "2024-03-20T22:29:56.051502",
          "updatedOn": null
        }
      ]
    },
    {
      "id": 1725,
      "name": "tayyip test",
      "shortDescription": "<p>Boş olamaz</p>\r\n",
      "type": 1,
      "link": null,
      "linkText": null,
      "details": []
    },
    {
      "id": 306,
      "name": "Yönlendirme görsel ve text test görkem",
      "shortDescription": "<p>test görkem</p>\r\n",
      "type": 16,
      "link": "https://www.hangikredi.com/",
      "linkText": null,
      "details": [
        {
          "id": 1994,
          "title": "HangiKredi mobil uygulaması ile tüm işlemler cebinde!",
          "subTitle": "sol",
          "description": "<p>Görkem İhtiyaç kredisi, kredi kartı, finansal rapo, fatura vb. tüm işlemlerini mobil uygulamadan kolaylıkla yapabilirsin.İhtiyaç kredisi, kredi kartı, finansal rapor fatura vb. tüm işlemlerini mobil uygulamadan kolaylıkla yapabilirsin.</p>\r\n\r\n<p></p>\r\n\r\n<p></p>\r\n\r\n<p></p>\r\n",
          "buttonText": "https://test.hangikredi.com/kredi-notu",
          "backgroundColor": null,
          "link": "https://play.google.com/store/apps/details?id=com.hangikredi ",
          "linkText": "google-play-link",
          "secondLink": "https://apps.apple.com/us/app/hangikredi/id1610287797",
          "secondLinkText": "apple-link",
          "thirdLink": "https://5u3m.adj.st/InvestmentHomePage?adj_t=1dcuoui1&adj_deep_link=hangikrediapp%3A%2F%2FInvestmentHomePage",
          "thirdLinkText": "Hemen İndirr",
          "linkTarget": "_self",
          "displayOrder": 1,
          "bankIdForBanksApps": "0",
          "buttonIsActive": true,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com/images/widget/1c5fe413-bf76-42c8-8e84-b11c7cb1566a-desktop.png",
          "createdOn": "2022-11-15T12:43:48.943223",
          "updatedOn": "2025-01-20T15:52:11.875835"
        },
        {
          "id": 1977,
          "title": "Kredi Skoru Hesaplama",
          "subTitle": "sol",
          "description": "<p>HangiKredi sit amet HangiKredi consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore. lorem ipsum dolor sit amet consectetur adipiscing. </p>\r\n\r\n<p></p>\r\n\r\n<p></p>\r\n",
          "buttonText": "Hesapla",
          "backgroundColor": null,
          "link": "https://test.hangikredi.com/kredi-notu",
          "linkText": "Hesapla",
          "secondLink": null,
          "secondLinkText": null,
          "thirdLink": "Hemen İndir",
          "thirdLinkText": null,
          "linkTarget": "_blank",
          "displayOrder": 2,
          "bankIdForBanksApps": "0",
          "buttonIsActive": false,
          "secondButtonIsActive": false,
          "secondButtonText": null,
          "popUpText": null,
          "imagePath": "https://test-hkcdn.mncdn.com/images/widget/4a549871-21c2-400b-ac7e-d62839a221d8-desktop.png",
          "createdOn": "2022-06-15T08:29:07.862773",
          "updatedOn": "2025-02-20T12:36:53.436425"
        }
      ]
    }
  ],
  "sliders": [
    {
      "id": 227,
      "name": "testbp",
      "link": "http://testbackoffice.hangikredi.com/",
      "imagePath": "https://test-hkcdn.mncdn.com/images/slider/b6eb31fd-a31e-44b1-912b-175a5ae52fac-desktop.png",
      "alternateText": "testbp",
      "displayOrder": 7,
      "linkTarget": null,
      "isSendEvent": false,
      "isShowPopUp": false,
      "popUpTitle": null,
      "popUpDescription": null,
      "popUpButtonText": null,
      "popUpButtonColor": null
    },
    {
      "id": 133,
      "name": "ING e-Turuncu Hesap",
      "link": "https://www.ing.com.tr/tr/isiniz-icin/kobi-eturuncu-basvuru-formu?utm_source=hangikredi-nativecard&utm_medium=nativecard%20&utm_campaign=eturuncu",
      "imagePath": "https://test-hkcdn.mncdn.com/images/slider/ad73acb5-80d2-4698-9114-c918c6c573c2-desktop.svg",
      "alternateText": null,
      "displayOrder": 56,
      "linkTarget": null,
      "isSendEvent": false,
      "isShowPopUp": false,
      "popUpTitle": null,
      "popUpDescription": null,
      "popUpButtonText": null,
      "popUpButtonColor": null
    }
  ],
  "creditAnalysisCard": {
    "amountMinimum": 1,
    "amountMaximum": 100000000,
    "maturityMinimum": 1,
    "maturityMaximum": 48,
    "minimumAnnualCostRate": 0.01,
    "maximumAnnualCostRate": 125.22,
    "financeType": 1,
    "suggested": {
      "amount": 10000,
      "annualCostRate": 0.01,
      "interestRate": 0,
      "maturity": 36,
      "monthlyInstallment": 277.78,
      "totalAmountWithoutExpense": 10000,
      "totalExpense": 0,
      "totalAmount": 10000
    }
  },
  "nativeCards": [
    {
      "id": 821,
      "pageId": 293,
      "type": 2,
      "name": "En Düşük Faiz",
      "deviceStatus": 2,
      "redirectionType": 0,
      "categoryId": 6,
      "productId": 158,
      "bankId": 30,
      "bankName": null,
      "bankLogoPath": null,
      "link": "/kredi-karti/akbank/paraf-business",
      "linkType": 1,
      "target": null,
      "listViewOrder": 0,
      "isActiveRecourse": true,
      "recourseLink": "/basvuru/nativecard/kredi-karti?Id=821&bankId=30",
      "wenUnitRevenue": 0,
      "appUnitRevenue": 0,
      "maturityMinimum": null,
      "maturityMaximum": null,
      "amountMinimum": null,
      "amountMaximum": null,
      "alternativeCategoryId": 0,
      "alternativeProductId": 0,
      "alternativeProductIsShowSponsor": false,
      "alternativeProductSponsorText": null,
      "rate": "%0 (Faizsiz)",
      "maturity": 21,
      "amount": 40000,
      "productType": 6,
      "productTypeText": null,
      "isOfferPopUp": false,
      "offerRateText": "Faiz Oranı",
      "offerAmountText": null,
      "offerCTAText": "Müşteri Ol",
      "offerProductName": "En Düşük Faiz",
      "offerSpecialDescription": null,
      "isShowSponsor": false,
      "conditions": "<p>Gösterilen ürün ve kampanya bilgileri banka tarafından iletilmekte olup kampanya katılım şartlarına ve banka kredi tahsis politikalarına göre değişkenlik gösterebilir.</p>\r\n\r\n<p><strong>%0 Faizli 35.000 TL’ye Kadar Kredi - Kampanya Detayları;</strong></p>\r\n\r\n<ul>\r\n\t<li>Kampanya 10 - 28 Şubat 2025 tarihleri arasında geçerlidir.</li>\r\n\t<li>Kampanya sadece henüz Enpara müşterisi olmayan kişilerin HangiKredi üzerinden yapacağı ihtiyaç kredisi başvuruları için geçerlidir.</li>\r\n\t<li>Kampanya kapsamında %0 faizli (faizsiz) olarak kullanılabilecek maksimum kredi tutarı 35.000 TL, maksimum vade ise 6 aydır.</li>\r\n\t<li>Başvurunuzun başlangıç aşamasında yapılan ön değerlendirme (kredi skorlaması) sonucunda başvuruya devam edebileceğiniz kredi tutarı ve vadesi Enpara.com tarafından belirlenerek size bildirilir.</li>\r\n\t<li>Enpara.com ihtiyaç kredisinde tahsis ücreti veya dosya masrafı yoktur.</li>\r\n\t<li>Bu kampanya kapsamındaki ihtiyaç kredilerinde hayat sigortası bulunmaktadır.</li>\r\n\t<li>Enpara.com kampanya koşullarında değişiklik yapma/sonlandırma hakkını saklı tutar.</li>\r\n</ul>\r\n\r\n<p>Başvuru değerlendirmesi yukarıdaki koşullara uygun olarak banka tarafından yapılır ve banka kredi tahsis politikasına göre sonuçlandırılır. HangiKredi’nin bu kapsamda herhangi bir sorumluluğu bulunmamakta olup HangiKredi bankalara destek hizmeti sunan bir kuruluştur. Web sitemiz ve uygulamamız üzerinden banka ürünlerinin karşılaştırılması, kullanıcı tercihi doğrultusunda başvuruların güvenli bir şekilde bankalara iletilmesi sağlanmaktadır. </p>\r\n",
      "isConditionActive": true,
      "nativeCardOfferCampaigns": [],
      "nativeCardPictures": {
        "desktopImagePath": null,
        "mobileImagePath": null,
        "tabletImagePath": null,
        "qrImagePath": null,
        "altTitle": null
      },
      "nativeCardAttributes": [],
      "isActiveInformationTooltip": true,
      "informationTooltipText": "Test Tooltip",
      "informationTooltipLeftToRight": null,
      "informationTooltipTopToDown": null
    },
    {
      "id": 807,
      "pageId": 293,
      "type": 2,
      "name": "Alternatif Bank Sıfır Faizli Fırsatlar",
      "deviceStatus": 2,
      "redirectionType": 1,
      "categoryId": 1,
      "productId": -1,
      "bankId": 7,
      "bankName": "Garanti Bankası",
      "bankLogoPath": "https://test-hkcdn.mncdn.com/images/bank/garanti-1.svg",
      "link": "https://www.hangikredi.com/basvuru/hkyonlendirme?Id=32&ct=nativekart&bankId=16",
      "linkType": 1,
      "target": "_blank",
      "listViewOrder": 0,
      "isActiveRecourse": true,
      "recourseLink": "/basvuru/nativecard?Id=807&bankId=7",
      "wenUnitRevenue": 0,
      "appUnitRevenue": 0,
      "maturityMinimum": null,
      "maturityMaximum": null,
      "amountMinimum": null,
      "amountMaximum": null,
      "alternativeCategoryId": 0,
      "alternativeProductId": 0,
      "alternativeProductIsShowSponsor": false,
      "alternativeProductSponsorText": null,
      "rate": "%0(Faizsiz)",
      "maturity": 3,
      "amount": 45000,
      "productType": 3,
      "productTypeText": "Faizsiz Fırsat",
      "isOfferPopUp": false,
      "offerRateText": "Faiz Oranı",
      "offerAmountText": "Toplam",
      "offerCTAText": "Müşteri Ol 2",
      "offerProductName": "Özel Oran",
      "offerSpecialDescription": null,
      "isShowSponsor": false,
      "conditions": "<p>Gösterilen ürün ve kampanya bilgileri banka tarafından iletilmekte olup kampanya katılım şartlarına ve banka kredi tahsis politikalarına göre değişkenlik gösterebilir.</p>\r\n\r\n<p><strong>%0 Faizli 35.000 TL’ye Kadar Kredi - Kampanya Detayları;</strong></p>\r\n\r\n<ul>\r\n\t<li>Kampanya 10 - 28 Şubat 2025 tarihleri arasında geçerlidir.</li>\r\n\t<li>Kampanya sadece henüz Enpara müşterisi olmayan kişilerin HangiKredi üzerinden yapacağı ihtiyaç kredisi başvuruları için geçerlidir.</li>\r\n\t<li>Kampanya kapsamında %0 faizli (faizsiz) olarak kullanılabilecek maksimum kredi tutarı 35.000 TL, maksimum vade ise 6 aydır.</li>\r\n\t<li>Başvurunuzun başlangıç aşamasında yapılan ön değerlendirme (kredi skorlaması) sonucunda başvuruya devam edebileceğiniz kredi tutarı ve vadesi Enpara.com tarafından belirlenerek size bildirilir.</li>\r\n\t<li>Enpara.com ihtiyaç kredisinde tahsis ücreti veya dosya masrafı yoktur.</li>\r\n\t<li>Bu kampanya kapsamındaki ihtiyaç kredilerinde hayat sigortası bulunmaktadır.</li>\r\n\t<li>Enpara.com kampanya koşullarında değişiklik yapma/sonlandırma hakkını saklı tutar.</li>\r\n</ul>\r\n\r\n<p>Başvuru değerlendirmesi yukarıdaki koşullara uygun olarak banka tarafından yapılır ve banka kredi tahsis politikasına göre sonuçlandırılır. HangiKredi’nin bu kapsamda herhangi bir sorumluluğu bulunmamakta olup HangiKredi bankalara destek hizmeti sunan bir kuruluştur. Web sitemiz ve uygulamamız üzerinden banka ürünlerinin karşılaştırılması, kullanıcı tercihi doğrultusunda başvuruların güvenli bir şekilde bankalara iletilmesi sağlanmaktadır. </p>\r\n",
      "isConditionActive": true,
      "nativeCardOfferCampaigns": [],
      "nativeCardPictures": {
        "desktopImagePath": null,
        "mobileImagePath": null,
        "tabletImagePath": null,
        "qrImagePath": "https://test-hkcdn.mncdn.com/images/content/nativecard/26a0be36-cc85-418f-b02b-ce09db76d8e8.png",
        "altTitle": null
      },
      "nativeCardAttributes": [],
      "isActiveInformationTooltip": false,
      "informationTooltipText": null,
      "informationTooltipLeftToRight": null,
      "informationTooltipTopToDown": null
    },
    {
      "id": 801,
      "pageId": 293,
      "type": 2,
      "name": "QNB Finansbank Sıfır Faizli Fırsatlar",
      "deviceStatus": 2,
      "redirectionType": 1,
      "categoryId": 1,
      "productId": -1,
      "bankId": 16,
      "bankName": "QNB Finansbank",
      "bankLogoPath": "https://test-hkcdn.mncdn.com/images/bank/qnb.svg",
      "link": "https://www.hangikredi.com/basvuru/hkyonlendirme?Id=32&ct=nativekart&bankId=16",
      "linkType": 1,
      "target": "_blank",
      "listViewOrder": 0,
      "isActiveRecourse": true,
      "recourseLink": "/basvuru/nativecard?Id=801&bankId=16",
      "wenUnitRevenue": 0,
      "appUnitRevenue": 0,
      "maturityMinimum": null,
      "maturityMaximum": null,
      "amountMinimum": null,
      "amountMaximum": null,
      "alternativeCategoryId": 0,
      "alternativeProductId": 0,
      "alternativeProductIsShowSponsor": false,
      "alternativeProductSponsorText": null,
      "rate": "%0(Faizsiz)",
      "maturity": 3,
      "amount": 45000,
      "productType": 0,
      "productTypeText": "Faizsiz Fırsat",
      "isOfferPopUp": true,
      "offerRateText": "Faiz Oranı",
      "offerAmountText": null,
      "offerCTAText": "Müşteri Ol 1",
      "offerProductName": "Ayın Ürünü",
      "offerSpecialDescription": "Test Ayın Ürünü Özel Açıklama",
      "isShowSponsor": true,
      "conditions": "<p><strong>%0 Faizli 35.000 TL’ye Kadar Kredi - Kampanya Detayları;</strong></p>\r\n\r\n<ul>\r\n\t<li>Kampanya 10 - 28 Şubat 2025 tarihleri arasında geçerlidir.</li>\r\n\t<li>Kampanya sadece henüz Enpara müşterisi olmayan kişilerin HangiKredi üzerinden yapacağı ihtiyaç kredisi başvuruları için geçerlidir.</li>\r\n\t<li>Kampanya kapsamında %0 faizli (faizsiz) olarak kullanılabilecek maksimum kredi tutarı 35.000 TL, maksimum vade ise 6 aydır.</li>\r\n\t<li>Başvurunuzun başlangıç aşamasında yapılan ön değerlendirme (kredi skorlaması) sonucunda başvuruya devam edebileceğiniz kredi tutarı ve vadesi Enpara.com tarafından belirlenerek size bildirilir.</li>\r\n\t<li>Enpara.com ihtiyaç kredisinde tahsis ücreti veya dosya masrafı yoktur.</li>\r\n\t<li>Bu kampanya kapsamındaki ihtiyaç kredilerinde hayat sigortası bulunmaktadır.</li>\r\n\t<li>Enpara.com kampanya koşullarında değişiklik yapma/sonlandırma hakkını saklı tutar.</li>\r\n</ul>\r\n\r\n<p>Başvuru değerlendirmesi yukarıdaki koşullara uygun olarak banka tarafından yapılır ve banka kredi tahsis politikasına göre sonuçlandırılır. HangiKredi’nin bu kapsamda herhangi bir sorumluluğu bulunmamakta olup HangiKredi bankalara destek hizmeti sunan bir kuruluştur. Web sitemiz ve uygulamamız üzerinden banka ürünlerinin karşılaştırılması, kullanıcı tercihi doğrultusunda başvuruların güvenli bir şekilde bankalara iletilmesi sağlanmaktadır. </p>\r\n",
      "isConditionActive": true,
      "nativeCardOfferCampaigns": [],
      "nativeCardPictures": {
        "desktopImagePath": null,
        "mobileImagePath": null,
        "tabletImagePath": null,
        "qrImagePath": "https://test-hkcdn.mncdn.com/images/qrgenerator/e50c6857-b512-43eb-aa38-7ea6d2ec7ef0.png",
        "altTitle": null
      },
      "nativeCardAttributes": [],
      "isActiveInformationTooltip": true,
      "informationTooltipText": "Test Tooltip",
      "informationTooltipLeftToRight": null,
      "informationTooltipTopToDown": null
    },
    {
      "id": 803,
      "pageId": 293,
      "type": 2,
      "name": "Denizbank Sıfır Faizli Fırsatlar",
      "deviceStatus": 2,
      "redirectionType": 1,
      "categoryId": 1,
      "productId": -1,
      "bankId": 11,
      "bankName": "DenizBank",
      "bankLogoPath": "https://test-hkcdn.mncdn.com/images/bank/denizbank.svg",
      "link": "https://mza5.tr.adj.st/akbankdirekt?function=609&adj_t=u9hmept&adj_deep_link=akbankdirekt%3A%2F%2Fsplash%2Ffunction%2F609&adj_campaign=dobsayfasi&adj_fallback=https%3A%2F%2Fwww.akbank.com%2Fbasvuru%2Fmobileappservice%2F%23&adj_install_callback=https%3A%2F%2Freporting.hangikredi.com%2Fadjust%2Fapi%2Fcallback%3Fgps_adid%3D%7Bgps_adid%7D%26idfa%3D%7Bidfa%7D%26tracker_name%3D%7Btracker_name%7D%26app_name%3D%7Bapp_name%7D%26campaign_name%3D%7Bcampaign_name%7D%26adgroup%3D%7Badgroup_name%7D%26creative%3D%7Bcreative_name%7D%26activity_kind%3D%7Bactivity_kind%7D%26created_at%3D%7Bcreated_at%7D%26installed_at%3D%7Binstalled_at%7D%26installed_at_hour%3D%7Binstalled_at_hour%7D%26click_id%3Dorganik",
      "linkType": 1,
      "target": "_blank",
      "listViewOrder": 0,
      "isActiveRecourse": true,
      "recourseLink": "/basvuru/nativecard/ihtiyac?Id=803&bankId=11",
      "wenUnitRevenue": 0,
      "appUnitRevenue": 0,
      "maturityMinimum": null,
      "maturityMaximum": null,
      "amountMinimum": null,
      "amountMaximum": null,
      "alternativeCategoryId": 0,
      "alternativeProductId": 0,
      "alternativeProductIsShowSponsor": false,
      "alternativeProductSponsorText": null,
      "rate": "%0(Faizsiz)",
      "maturity": 5,
      "amount": 25000,
      "productType": 2,
      "productTypeText": "Badge Namee",
      "isOfferPopUp": true,
      "offerRateText": "Faiz Oranı",
      "offerAmountText": "Toplam",
      "offerCTAText": "Müşteri Ol",
      "offerProductName": "Yeni Müşterilere Özel",
      "offerSpecialDescription": null,
      "isShowSponsor": false,
      "conditions": null,
      "isConditionActive": false,
      "nativeCardOfferCampaigns": [],
      "nativeCardPictures": {
        "desktopImagePath": null,
        "mobileImagePath": null,
        "tabletImagePath": null,
        "qrImagePath": "https://test-hkcdn.mncdn.com/images/content/nativecard/33d61e42-fca9-4649-8bd4-86582a74c9cc.svg",
        "altTitle": null
      },
      "nativeCardAttributes": [],
      "isActiveInformationTooltip": false,
      "informationTooltipText": null,
      "informationTooltipLeftToRight": null,
      "informationTooltipTopToDown": null
    },
    {
      "id": 808,
      "pageId": 293,
      "type": 2,
      "name": "En Para Sıfır Faizli Fırsatlar",
      "deviceStatus": 2,
      "redirectionType": 1,
      "categoryId": 1,
      "productId": -1,
      "bankId": 13,
      "bankName": "Enpara.com",
      "bankLogoPath": "https://test-hkcdn.mncdn.com/images/bank/enpara.svg",
      "link": "https://www.hangikredi.com/basvuru/hkyonlendirme?Id=32&ct=nativekart&bankId=16",
      "linkType": 1,
      "target": "_blank",
      "listViewOrder": 1,
      "isActiveRecourse": true,
      "recourseLink": "/basvuru/nativecard?Id=808&bankId=13",
      "wenUnitRevenue": 0,
      "appUnitRevenue": 0,
      "maturityMinimum": null,
      "maturityMaximum": null,
      "amountMinimum": null,
      "amountMaximum": null,
      "alternativeCategoryId": 0,
      "alternativeProductId": 0,
      "alternativeProductIsShowSponsor": false,
      "alternativeProductSponsorText": null,
      "rate": "%0(Faizsiz)",
      "maturity": 3,
      "amount": 45000,
      "productType": 0,
      "productTypeText": "Faizsiz Fırsat",
      "isOfferPopUp": false,
      "offerRateText": "Faiz Oranı",
      "offerAmountText": "Toplam",
      "offerCTAText": "Müşteri Ol",
      "offerProductName": "Ayın Ürünü",
      "offerSpecialDescription": null,
      "isShowSponsor": false,
      "conditions": null,
      "isConditionActive": false,
      "nativeCardOfferCampaigns": [
        {
          "description": "<strong>3 ay</strong> vadeli, <strong>25.000 TL</strong> taksitli nakit avans!",
          "displayOrder": 1,
          "type": 1
        },
        {
          "description": "<strong>6 ay </strong>vadeli, <strong>20.000 TL</strong> kredi!",
          "displayOrder": 2,
          "type": 1
        }
      ],
      "nativeCardPictures": {
        "desktopImagePath": null,
        "mobileImagePath": null,
        "tabletImagePath": null,
        "qrImagePath": "https://test-hkcdn.mncdn.com/images/content/nativecard/e20781aa-70f5-4317-83a7-0b48be7e6161.svg",
        "altTitle": null
      },
      "nativeCardAttributes": [],
      "isActiveInformationTooltip": false,
      "informationTooltipText": null,
      "informationTooltipLeftToRight": null,
      "informationTooltipTopToDown": null
    }
  ],
  "pageId": 293,
  "page": {
    "id": 293,
    "code": "zero-interest-opportunity",
    "name": "%0 Faizli Fırsatlar",
    "category": "Kredi",
    "midCategory": "İhtiyaç Kredisi",
    "subCategory": "0 Faizli Fırsatlar",
    "type": "Listing",
    "pageType": null,
    "sharingType": "WebSite",
    "heroButtonText": null,
    "whatIsTitle": null,
    "desktopImagePath1": null,
    "mobileImagePath1": null,
    "desktopImagePath2": null,
    "mobileImagePath2": null,
    "mobileAdvertisementRefresh": null,
    "webAdvertisementRefresh": null
  },
  "seoInfo": {
    "title": "Sıfır Faizli Fırsatlar",
    "metaDescription": "HangiKredi Sıfır Faizli Fırsatlar sayfası ile teklifleri inceleyin, dilediğiniz bankaya hemen başvurun!",
    "canonicalUrl": "https://www.hangikredi.com/sifir-faizli-firsatlar",
    "headingTitle": "%0 Faizli Kredi",
    "heroDescription": null,
    "friendlyUrl": null,
    "entity": null,
    "entityId": null,
    "statusParameters": 0,
    "image": "https://statics-hangikredi.mncdn.com/images/hk-thumb-logo.png",
    "badge": null,
    "shortDesc": null,
    "page": null
  },
  "advertisements": [
    {
      "id": 212,
      "type": 1,
      "deviceType": 1,
      "elementId": "adsZeroInterest-1",
      "height": null,
      "width": null,
      "advertisementScript": {
        "id": 15,
        "name": "hk_w_listing1_300x250",
        "headerCode": "googletag.defineSlot('/21155722/hangikredi.com/hk_w_listing1_300x250', [[300, 600], [300, 250]], 'div-gpt-ad-1628697048253-0').addService(googletag.pubads());",
        "bodyCode": "div-gpt-ad-1628697048253-1"
      },
      "isLazyStatus": false
    }
  ],
  "bankPartners": [],
  "breadCrumb": [
    {
      "item": "Anasayfa",
      "url": "https://test.hangikredi.com"
    },
    {
      "item": "Sıfır Faizli Fırsatlar",
      "url": "https://test.hangikredi.com/sifir-faizli-firsatlar"
    }
  ],
  "parityBandModule": []
}; 